# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='frameconf.proto',
  package='',
  serialized_pb='\n\x0f\x66rameconf.proto\"$\n\tFrameConf\x12\x17\n\x0f\x66rames_recieved\x18\x01 \x01(\x04')




_FRAMECONF = descriptor.Descriptor(
  name='FrameConf',
  full_name='FrameConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='frames_recieved', full_name='FrameConf.frames_recieved', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['FrameConf'] = _FRAMECONF

class FrameConf(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRAMECONF
  
  # @@protoc_insertion_point(class_scope:FrameConf)

# @@protoc_insertion_point(module_scope)
