# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='MobileId.proto',
  package='',
  serialized_pb='\n\x0eMobileId.proto\"\x18\n\x08MobileId\x12\x0c\n\x04imei\x18\x01 \x01(\t')




_MOBILEID = descriptor.Descriptor(
  name='MobileId',
  full_name='MobileId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='imei', full_name='MobileId.imei', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=42,
)

DESCRIPTOR.message_types_by_name['MobileId'] = _MOBILEID

class MobileId(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOBILEID
  
  # @@protoc_insertion_point(class_scope:MobileId)

# @@protoc_insertion_point(module_scope)
