# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='trackevent.proto',
  package='',
  serialized_pb='\n\x10trackevent.proto\"\x8b\x01\n\nTrackEvent\x12 \n\x05\x65vent\x18\x01 \x02(\x0e\x32\x11.TrackEvent.Event\x12\n\n\x02id\x18\x02 \x02(\x0c\x12\x11\n\ttimestamp\x18\x03 \x02(\r\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"+\n\x05\x45vent\x12\x11\n\rTRACK_STARTED\x10\x00\x12\x0f\n\x0bTRACK_ENDED\x10\x01')



_TRACKEVENT_EVENT = descriptor.EnumDescriptor(
  name='Event',
  full_name='TrackEvent.Event',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='TRACK_STARTED', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRACK_ENDED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=117,
  serialized_end=160,
)


_TRACKEVENT = descriptor.Descriptor(
  name='TrackEvent',
  full_name='TrackEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='event', full_name='TrackEvent.event', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='TrackEvent.id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='TrackEvent.timestamp', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='TrackEvent.payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRACKEVENT_EVENT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=160,
)

_TRACKEVENT.fields_by_name['event'].enum_type = _TRACKEVENT_EVENT
_TRACKEVENT_EVENT.containing_type = _TRACKEVENT;
DESCRIPTOR.message_types_by_name['TrackEvent'] = _TRACKEVENT

class TrackEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKEVENT
  
  # @@protoc_insertion_point(class_scope:TrackEvent)

# @@protoc_insertion_point(module_scope)
