# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='trackinfo.proto',
  package='',
  serialized_pb='\n\x0ftrackinfo.proto\"+\n\tTrackInfo\x12\r\n\x05sport\x18\x01 \x01(\r\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t')




_TRACKINFO = descriptor.Descriptor(
  name='TrackInfo',
  full_name='TrackInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sport', full_name='TrackInfo.sport', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='TrackInfo.comment', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['TrackInfo'] = _TRACKINFO

class TrackInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKINFO
  
  # @@protoc_insertion_point(class_scope:TrackInfo)

# @@protoc_insertion_point(module_scope)
