# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='pathchunk.proto',
  package='',
  serialized_pb='\n\x0fpathchunk.proto\"\xd5\x02\n\x08PathCunk\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x06 \x01(\x04\x12\x0f\n\x07session\x18\x07 \x01(\x04\x12\x11\n\ttime_base\x18\x02 \x01(\r\x12\x10\n\x08lat_base\x18\x03 \x01(\x02\x12\x11\n\tlong_base\x18\x04 \x01(\x02\x12\x10\n\x08\x61lt_base\x18\x05 \x01(\r\x12\x15\n\tangle_div\x18\x10 \x01(\r:\x02\x31\x36\x12\x14\n\ttime_step\x18\x11 \x01(\r:\x01\x31\x12\"\n\x05point\x18\n \x03(\x0b\x32\x13.PathCunk.CunkPoint\x1a\x81\x01\n\tCunkPoint\x12\x12\n\x06packed\x18\x01 \x03(\x11\x42\x02\x10\x01\x12\x10\n\x08\x61lt_base\x18\x02 \x01(\x11\"N\n\x0cPackedFields\x12\x08\n\x04TIME\x10\x00\x12\x07\n\x03LAT\x10\x01\x12\x08\n\x04LONG\x10\x02\x12\x07\n\x03\x41LT\x10\x03\x12\x18\n\x14PACKED_FIELDS_NUMBER\x10\x04\"3\n\x0cPathCunkConf\x12\x12\n\nlast_index\x18\x01 \x01(\x04\x12\x0f\n\x07session\x18\x02 \x01(\x04')



_PATHCUNK_CUNKPOINT_PACKEDFIELDS = descriptor.EnumDescriptor(
  name='PackedFields',
  full_name='PathCunk.CunkPoint.PackedFields',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='TIME', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LAT', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LONG', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ALT', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PACKED_FIELDS_NUMBER', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=283,
  serialized_end=361,
)


_PATHCUNK_CUNKPOINT = descriptor.Descriptor(
  name='CunkPoint',
  full_name='PathCunk.CunkPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='packed', full_name='PathCunk.CunkPoint.packed', index=0,
      number=1, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    descriptor.FieldDescriptor(
      name='alt_base', full_name='PathCunk.CunkPoint.alt_base', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PATHCUNK_CUNKPOINT_PACKEDFIELDS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=232,
  serialized_end=361,
)

_PATHCUNK = descriptor.Descriptor(
  name='PathCunk',
  full_name='PathCunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='PathCunk.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='index', full_name='PathCunk.index', index=1,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session', full_name='PathCunk.session', index=2,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time_base', full_name='PathCunk.time_base', index=3,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lat_base', full_name='PathCunk.lat_base', index=4,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='long_base', full_name='PathCunk.long_base', index=5,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='alt_base', full_name='PathCunk.alt_base', index=6,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='angle_div', full_name='PathCunk.angle_div', index=7,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=16,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time_step', full_name='PathCunk.time_step', index=8,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point', full_name='PathCunk.point', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PATHCUNK_CUNKPOINT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=361,
)


_PATHCUNKCONF = descriptor.Descriptor(
  name='PathCunkConf',
  full_name='PathCunkConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='last_index', full_name='PathCunkConf.last_index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session', full_name='PathCunkConf.session', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=363,
  serialized_end=414,
)

_PATHCUNK_CUNKPOINT.containing_type = _PATHCUNK;
_PATHCUNK_CUNKPOINT_PACKEDFIELDS.containing_type = _PATHCUNK_CUNKPOINT;
_PATHCUNK.fields_by_name['point'].message_type = _PATHCUNK_CUNKPOINT
DESCRIPTOR.message_types_by_name['PathCunk'] = _PATHCUNK
DESCRIPTOR.message_types_by_name['PathCunkConf'] = _PATHCUNKCONF

class PathCunk(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class CunkPoint(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PATHCUNK_CUNKPOINT
    
    # @@protoc_insertion_point(class_scope:PathCunk.CunkPoint)
  DESCRIPTOR = _PATHCUNK
  
  # @@protoc_insertion_point(class_scope:PathCunk)

class PathCunkConf(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PATHCUNKCONF
  
  # @@protoc_insertion_point(class_scope:PathCunkConf)

# @@protoc_insertion_point(module_scope)
