# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='RpcMessage.proto',
  package='ProtoBufRemote',
  serialized_pb='\n\x10RpcMessage.proto\x12\x0eProtoBufRemote\"\xcf\x04\n\nRpcMessage\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x35\n\x0c\x63\x61ll_message\x18\x02 \x01(\x0b\x32\x1f.ProtoBufRemote.RpcMessage.Call\x12\x39\n\x0eresult_message\x18\x03 \x01(\x0b\x32!.ProtoBufRemote.RpcMessage.Result\x1ay\n\x04\x43\x61ll\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x02(\t\x12\x38\n\nparameters\x18\x03 \x03(\x0b\x32$.ProtoBufRemote.RpcMessage.Parameter\x12\x16\n\x0e\x65xpects_result\x18\x04 \x02(\x08\x1am\n\x06Result\x12\x11\n\tis_failed\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x39\n\x0b\x63\x61ll_result\x18\x03 \x01(\x0b\x32$.ProtoBufRemote.RpcMessage.Parameter\x1a\xd8\x01\n\tParameter\x12\x13\n\x0bproto_param\x18\x01 \x01(\x0c\x12\x14\n\x0cstring_param\x18\x02 \x01(\t\x12\x11\n\tint_param\x18\x03 \x01(\x11\x12\x12\n\nuint_param\x18\x04 \x01(\r\x12\x13\n\x0bint64_param\x18\x05 \x01(\x12\x12\x14\n\x0cuint64_param\x18\x06 \x01(\x04\x12\x12\n\nbool_param\x18\x07 \x01(\x08\x12\x13\n\x0b\x66loat_param\x18\x08 \x01(\x02\x12\x14\n\x0c\x64ouble_param\x18\t \x01(\x01\x12\x0f\n\x07is_null\x18\n \x01(\x08')




_RPCMESSAGE_CALL = descriptor.Descriptor(
  name='Call',
  full_name='ProtoBufRemote.RpcMessage.Call',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service', full_name='ProtoBufRemote.RpcMessage.Call.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='method', full_name='ProtoBufRemote.RpcMessage.Call.method', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parameters', full_name='ProtoBufRemote.RpcMessage.Call.parameters', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expects_result', full_name='ProtoBufRemote.RpcMessage.Call.expects_result', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=177,
  serialized_end=298,
)

_RPCMESSAGE_RESULT = descriptor.Descriptor(
  name='Result',
  full_name='ProtoBufRemote.RpcMessage.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='is_failed', full_name='ProtoBufRemote.RpcMessage.Result.is_failed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_message', full_name='ProtoBufRemote.RpcMessage.Result.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='call_result', full_name='ProtoBufRemote.RpcMessage.Result.call_result', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=300,
  serialized_end=409,
)

_RPCMESSAGE_PARAMETER = descriptor.Descriptor(
  name='Parameter',
  full_name='ProtoBufRemote.RpcMessage.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='proto_param', full_name='ProtoBufRemote.RpcMessage.Parameter.proto_param', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='string_param', full_name='ProtoBufRemote.RpcMessage.Parameter.string_param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int_param', full_name='ProtoBufRemote.RpcMessage.Parameter.int_param', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uint_param', full_name='ProtoBufRemote.RpcMessage.Parameter.uint_param', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int64_param', full_name='ProtoBufRemote.RpcMessage.Parameter.int64_param', index=4,
      number=5, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uint64_param', full_name='ProtoBufRemote.RpcMessage.Parameter.uint64_param', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bool_param', full_name='ProtoBufRemote.RpcMessage.Parameter.bool_param', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='float_param', full_name='ProtoBufRemote.RpcMessage.Parameter.float_param', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='double_param', full_name='ProtoBufRemote.RpcMessage.Parameter.double_param', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_null', full_name='ProtoBufRemote.RpcMessage.Parameter.is_null', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=412,
  serialized_end=628,
)

_RPCMESSAGE = descriptor.Descriptor(
  name='RpcMessage',
  full_name='ProtoBufRemote.RpcMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='ProtoBufRemote.RpcMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='call_message', full_name='ProtoBufRemote.RpcMessage.call_message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result_message', full_name='ProtoBufRemote.RpcMessage.result_message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RPCMESSAGE_CALL, _RPCMESSAGE_RESULT, _RPCMESSAGE_PARAMETER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=628,
)

_RPCMESSAGE_CALL.fields_by_name['parameters'].message_type = _RPCMESSAGE_PARAMETER
_RPCMESSAGE_CALL.containing_type = _RPCMESSAGE;
_RPCMESSAGE_RESULT.fields_by_name['call_result'].message_type = _RPCMESSAGE_PARAMETER
_RPCMESSAGE_RESULT.containing_type = _RPCMESSAGE;
_RPCMESSAGE_PARAMETER.containing_type = _RPCMESSAGE;
_RPCMESSAGE.fields_by_name['call_message'].message_type = _RPCMESSAGE_CALL
_RPCMESSAGE.fields_by_name['result_message'].message_type = _RPCMESSAGE_RESULT
DESCRIPTOR.message_types_by_name['RpcMessage'] = _RPCMESSAGE

class RpcMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Call(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RPCMESSAGE_CALL
    
    # @@protoc_insertion_point(class_scope:ProtoBufRemote.RpcMessage.Call)
  
  class Result(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RPCMESSAGE_RESULT
    
    # @@protoc_insertion_point(class_scope:ProtoBufRemote.RpcMessage.Result)
  
  class Parameter(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RPCMESSAGE_PARAMETER
    
    # @@protoc_insertion_point(class_scope:ProtoBufRemote.RpcMessage.Parameter)
  DESCRIPTOR = _RPCMESSAGE
  
  # @@protoc_insertion_point(class_scope:ProtoBufRemote.RpcMessage)

# @@protoc_insertion_point(module_scope)
