# This is global configuration for gorynych.
# Motivation and usage in https://devc.ru/issues/3110
# This file must be a valid YAML file!
# Use 2 spaces while editing and don't use tabs!

# Default options which are common for system.
default:
  info:
    web_port: 8085

production:

# Personal settings for developers
develop:

# Test options
test:
    dbname: test_gorynych
    dbuser: postgres
    dbhost: localhost
    dbpassword: postgres
    dbport: 5432