CREATE TABLE CHATROOMS (
  ID SERIAL PRIMARY KEY ,
  CHATROOM_NAME TEXT NOT NULL UNIQUE
);

CREATE TABLE MESSAGES(
  ID BIGSERIAL PRIMARY KEY ,
  "FROM" TEXT NOT NULL ,
  SENDER TEXT NOT NULL ,
  "TO" TEXT ,
  BODY BYTEA NOT NULL ,
  TIMESTAMP INTEGER,
  CHATROOM_ID INT REFERENCES CHATROOMS (ID)
);


-- Insert message
INSERT INTO MESSAGES (
  "FROM", SENDER, "TO", BODY, TIMESTAMP, CHATROOM_ID)
    VALUES (%s, %s, %s, %s, %s,
            (SELECT ID FROM CHATROOMS WHERE CHATROOM_NAME=%s))
RETURNING ID;


-- Select message
SELECT
  m.ID, m."FROM", m.SENDER, m."TO", m.BODY, m.TIMESTAMP
FROM
  MESSAGES m,
  CHATROOMS c
WHERE
  c.CHATROOM_NAME = %s AND
  c.ID = m.CHATROOM_ID AND
  m.TIMESTAMP BETWEEN %s AND %s
ORDER BY m.TIMESTAMP;

