-- Aggregate Contest ------------------------------------

CREATE TABLE CONTEST(
  ID BIGSERIAL PRIMARY KEY,
  CONTEST_ID TEXT UNIQUE NOT NULL,
  TITLE TEXT,
  START_TIME INTEGER ,
  END_TIME INTEGER ,
  TIMEZONE TEXT,
  PLACE TEXT,
  COUNTRY TEXT,
  HQ_LAT REAL,
  HQ_LON REAL,

  UNIQUE (TITLE, START_TIME, END_TIME, COUNTRY)
);

CREATE TABLE CONTEST_PARAGLIDER(
  ID BIGINT REFERENCES CONTEST(ID) ON DELETE CASCADE,
  NAME TEXT NOT NULL,
  SURNAME TEXT NOT NULL,
  EMAIL TEXT UNIQUE,
  COUNTRY TEXT,
  PERSON_ID BIGINT REFERENCES PERSON(ID) ON DELETE CASCADE,
  GLIDER TEXT,
  CONTEST_NUMBER TEXT,
  DESCRIPTION TEXT,
  PHONE TEXT,

  PRIMARY KEY (ID, PERSON_ID)
);

CREATE TABLE CONTEST_TRANSPORT(
  ID BIGINT REFERENCES CONTEST(ID) ON DELETE CASCADE,
  TRANSPORT_ID BIGINT REFERENCES TRANSPORT(ID) ON DELETE CASCADE,
  TITLE TEXT NOT NULL,
  TYPE INT REFERENCES TRANSPORT_TYPE(ID) NOT NULL,
  DESCRIPTION TEXT,
  PHONE TEXT,

  PRIMARY KEY (ID, TRANSPORT_ID)
);

CREATE TABLE CONTEST_RETRIEVE_ID(
  ID BIGINT REFERENCES CONTEST(ID) ON DELETE CASCADE PRIMARY KEY ,
  RETRIEVE_ID TEXT
);

-- Insert Contest
INSERT INTO CONTEST(
  TITLE, START_TIME, END_TIME, TIMEZONE, PLACE, COUNTRY, HQ_LAT, HQ_LON, CONTEST_ID)
  VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
RETURNING ID;

-- Select Contest
SELECT * FROM CONTEST WHERE CONTEST_ID=%s;

-- Select all_contest
SELECT
  CONTEST_ID, ID, CONTEST_ID, TITLE, START_TIME, END_TIME, TIMEZONE, PLACE,
  COUNTRY, HQ_LAT, HQ_LON
FROM
  CONTEST;


-- Insert paragliders
INSERT INTO 
  CONTEST_PARAGLIDER(
    ID, PERSON_ID, NAME, SURNAME, EMAIL,
    COUNTRY, GLIDER, CONTEST_NUMBER, DESCRIPTION
  )
VALUES (
    %s,
    (SELECT id FROM PERSON WHERE PERSON.PERSON_ID=%s),
    %s, %s, %s, %s, %s, %s, %s, %s
  );

-- Select paragliders
SELECT
  (SELECT PERSON_ID FROM PERSON WHERE PERSON.ID=CONTEST_PARAGLIDER.PERSON_ID),
  NAME, SURNAME, EMAIL, COUNTRY, GLIDER, CONTEST_NUMBER, DESCRIPTION, PHONE
FROM
  CONTEST_PARAGLIDER
WHERE
  ID=%s;

-- Insert transport
INSERT INTO
  CONTEST_TRANSPORT(
    ID, TRANSPORT_ID, TITLE, TYPE, DESCRIPTION, PHONE
  )
VALUES (
    %s, (SELECT id FROM TRANSPORT WHERE TRANSPORT.TRANSPORT_ID=%s),
    %s, (SELECT id FROM TRANSPORT_TYPE where TRANSPORT_TYPE=%s), %s, %s
  );

-- Select transport
SELECT
  (SELECT TRANSPORT_ID FROM TRANSPORT WHERE TRANSPORT.ID=CONTEST_TRANSPORT.TRANSPORT_ID),
  TITLE, (SELECT TRANSPORT_TYPE FROM TRANSPORT_TYPE where TRANSPORT_TYPE.ID=CONTEST_TRANSPORT.TYPE),
  DESCRIPTION, PHONE
FROM
  CONTEST_TRANSPORT
WHERE
  ID=%s;

-- Update contest
UPDATE CONTEST SET (
  TITLE, START_TIME, END_TIME, TIMEZONE, PLACE, COUNTRY, HQ_LAT, HQ_LON)
= (%s, %s, %s, %s, %s, %s, %s, %s)
WHERE CONTEST_ID=%s;


-- Select retrieve_id
SELECT RETRIEVE_ID FROM CONTEST_RETRIEVE_ID WHERE ID=%s;


-- Select id_for_retrieve
SELECT CONTEST_ID
FROM
  CONTEST,
  CONTEST_RETRIEVE_ID
WHERE
  CONTEST_RETRIEVE_ID.RETRIEVE_ID = %s
  AND CONTEST_RETRIEVE_ID.ID = CONTEST.ID;