-- Aggregate Contest ------------------------------------

CREATE TABLE CONTEST(
  ID BIGSERIAL PRIMARY KEY,
  CONTEST_ID TEXT UNIQUE NOT NULL,
  TITLE TEXT,
  START_TIME INTEGER ,
  END_TIME INTEGER ,
  TIMEZONE TEXT,
  PLACE TEXT,
  COUNTRY TEXT,
  HQ_LAT REAL,
  HQ_LON REAL,
  RETRIEVE_ID TEXT,

  UNIQUE (TITLE, START_TIME, END_TIME, COUNTRY)
);

CREATE TABLE PARTICIPANT(
  ID BIGINT REFERENCES CONTEST(ID) ON DELETE CASCADE,
  PARTICIPANT_ID TEXT ,
  ROLE TEXT NOT NULL, -- paraglider, winddummy, staff, organizer
  -- for paragliders
  GLIDER TEXT,
  CONTEST_NUMBER TEXT ,
  -- for staff, organizer
  DESCRIPTION TEXT,
  TYPE TEXT , --staff's type
  PHONE TEXT ,
  NAME TEXT ,
  EMAIL TEXT,
  COUNTRY TEXT,
  TITLE TEXT, -- for staff

  PRIMARY KEY (ID, PARTICIPANT_ID)
);

CREATE UNIQUE INDEX UNIQUE_CONTEST_NUMBER ON PARTICIPANT (ID, CONTEST_NUMBER) WHERE ROLE='PARAGLIDER';

CREATE TABLE CONTEST_RETRIEVE_ID(
  ID BIGINT REFERENCES CONTEST(ID) ON DELETE CASCADE PRIMARY KEY ,
  RETRIEVE_ID TEXT
);

-- Insert Contest
INSERT INTO CONTEST(
  TITLE, START_TIME, END_TIME, TIMEZONE, PLACE, COUNTRY, HQ_LAT, HQ_LON, CONTEST_ID)
  VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
RETURNING ID;

-- Select Contest
SELECT * FROM CONTEST WHERE CONTEST_ID=%s;

-- Select all_contest
SELECT
  CONTEST_ID, ID, CONTEST_ID, TITLE, START_TIME, END_TIME, TIMEZONE, PLACE,
  COUNTRY, HQ_LAT, HQ_LON
FROM
  CONTEST;


-- Insert participant
INSERT INTO PARTICIPANT(
  ID, PARTICIPANT_ID, ROLE, GLIDER, CONTEST_NUMBER, DESCRIPTION, TYPE)
VALUES (
  (SELECT id FROM CONTEST WHERE CONTEST.CONTEST_ID=%s),
  %s, %s, %s, %s, %s, %s);

-- Select participants
SELECT * FROM PARTICIPANT WHERE ID=%s;


-- Update contest
UPDATE CONTEST SET (
  TITLE, START_TIME, END_TIME, TIMEZONE, PLACE, COUNTRY, HQ_LAT, HQ_LON)
= (%s, %s, %s, %s, %s, %s, %s, %s)
WHERE CONTEST_ID=%s;


-- Select retrieve_id
SELECT RETRIEVE_ID FROM CONTEST_RETRIEVE_ID WHERE ID=%s;


-- Select id_for_retrieve
SELECT CONTEST_ID
FROM
  CONTEST,
  CONTEST_RETRIEVE_ID
WHERE
  CONTEST_RETRIEVE_ID.RETRIEVE_ID = %s
  AND CONTEST_RETRIEVE_ID.ID = CONTEST.ID;