-- Don't comment this file on russian!
DROP SCHEMA IF EXISTS PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

-- Aggregate Tracker -------------------------------------------

CREATE TABLE DEVICE_TYPE(
	ID BIGSERIAL PRIMARY KEY,
	NAME TEXT
);

CREATE TABLE TRACKER(
  ID BIGSERIAL PRIMARY KEY,
  DEVICE_ID TEXT NOT NULL,
  DEVICE_TYPE BIGINT REFERENCES DEVICE_TYPE(ID) ON DELETE RESTRICT,
  NAME TEXT,
  TRACKER_ID TEXT UNIQUE NOT NULL,
  ASSIGNEE TEXT,

  UNIQUE (DEVICE_ID, DEVICE_TYPE)
);


-- Aggregate Person ---------------------------------------


CREATE TABLE PERSON(
  ID BIGSERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  SURNAME TEXT NOT NULL,
  REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EMAIL TEXT,
  COUNTRY TEXT,
  PERSON_ID TEXT UNIQUE NOT NULL
);

CREATE TABLE ASSIGNED_TRACKER(
  ID BIGINT REFERENCES PERSON(ID) ON DELETE CASCADE,
  TRACKER_ID TEXT NOT NULL,

  PRIMARY KEY (ID, TRACKER_ID)
);

CREATE TABLE PERSON_TRACKS(
  ID BIGINT REFERENCES PERSON(ID) ON DELETE CASCADE,
  TRACK_ID TEXT NOT NULL,

  PRIMARY KEY (ID, TRACK_ID)
);


-- Aggregate Contest ------------------------------------

CREATE TABLE CONTEST(
  ID BIGSERIAL PRIMARY KEY,
  CONTEST_ID TEXT UNIQUE NOT NULL,
  TITLE TEXT,
  START_TIME TIMESTAMPTZ,
  END_TIME TIMESTAMPTZ,
  PLACE TEXT,
  COUNTRY TEXT,
  HQ_LAT REAL,
  HQ_LON REAL
);

CREATE TABLE PARTICIPANT(
  ID BIGINT REFERENCES CONTEST(ID),
  PARTICIPANT_ID TEXT,
  ROLE TEXT NOT NULL,
  GLIDER TEXT,
  CONTEST_NUMBER TEXT,
  DESCRIPTION TEXT,
  TYPE TEXT NOT NULL,

  PRIMARY KEY (ID, PARTICIPANT_ID)
);

CREATE TABLE CONTEST_RACE(
  ID BIGINT REFERENCES CONTEST(ID),
  RACE_ID TEXT,

  PRIMARY KEY (RACE_ID, ID)
);


-- Aggregate Race --------------------------------------


CREATE TABLE RACE_TYPE(
  ID BIGSERIAL PRIMARY KEY,
  -- opendistance, racetogoal, speedrun etc.
  TYPE TEXT UNIQUE NOT NULL
);

CREATE TABLE RACE(
  ID BIGSERIAL PRIMARY KEY,
  RACE_ID TEXT UNIQUE NOT NULL,
  TITLE TEXT,
  START_TIME INTEGER NOT NULL,
  MIN_START_TIME TIMESTAMPTZ NOT NULL,
  END_TIME INTEGER NOT NULL,
  MAX_END_TIME TIMESTAMPTZ NOT NULL,
  RACE_TYPE BIGINT REFERENCES RACE_TYPE(ID),
  CHECKPOINTS TEXT NOT NULL
);

CREATE TABLE PARAGLIDER(
  ID BIGINT REFERENCES RACE(ID) ON DELETE CASCADE ,
  PERSON_ID TEXT NOT NULL,
  CONTEST_NUMBER TEXT,
  COUNTRY TEXT NOT NULL ,
  GLIDER TEXT ,
  TRACKER_ID TEXT ,
  NAME TEXT NOT NULL ,
  SURNAME TEXT NOT NULL ,

  PRIMARY KEY (ID, PERSON_ID)
);

CREATE TABLE PARAGLIDER_TRACKS (
  ID BIGINT REFERENCES RACE (ID) ON DELETE CASCADE,
  PERSON_ID TEXT REFERENCES paraglider(PERSON_ID) ON DELETE CASCADE ,
  TRACK_ID TEXT UNIQUE,

  PRIMARY KEY (ID, PERSON_ID)
);


-- Aggregate Track -------------------------------------

CREATE TABLE TRACK_TYPE(
  ID SERIAL PRIMARY KEY,
  NAME TEXT NOT NULL UNIQUE
);

insert into track_type (name) values('competition aftertask');

CREATE TABLE TRACK(
	ID BIGSERIAL PRIMARY KEY,
	START_TIME INTEGER ,
	END_TIME INTEGER ,
	TRACK_ID TEXT UNIQUE NOT NULL,
	TRACK_TYPE INT REFERENCES TRACK_TYPE(ID)
);

CREATE TABLE TRACK_DATA(
	ID BIGINT REFERENCES TRACK(ID) ON DELETE CASCADE ,
	TIMESTAMP INTEGER,
	LAT REAL,
	LON REAL,
	ALT SMALLINT ,
	G_SPEED REAL,
	V_SPEED REAL,
	DISTANCE REAL,

  PRIMARY KEY (TIMESTAMP, ID)
);

CREATE INDEX track_data_timestamp_idx
  ON track_data
  USING btree (timestamp);

CREATE TABLE TRACK_SNAPSHOT(
	ID BIGINT REFERENCES TRACK(ID),
	TIMESTAMP INTEGER ,
	SNAPSHOT TEXT NOT NULL,

  PRIMARY KEY (ID, TIMESTAMP)
);
