-- DB schema for gorynych.
-- Here I assume that database has been prepared already.

-- Aggregate Person ---------------------------------------

CREATE TABLE PERSON(
  ID BIGSERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  SURNAME TEXT NOT NULL,
  REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EMAIL TEXT,
  COUNTRY TEXT,
  PERSON_ID TEXT UNIQUE NOT NULL
);

CREATE TABLE ASSIGNED_TRACKER(
  ID BIGINT REFERENCES PERSON(ID) ON DELETE CASCADE,
  TRACKER_ID TEXT NOT NULL,

  PRIMARY KEY (ID, TRACKER_ID)
);

CREATE TABLE PERSON_TRACKS(
  ID BIGINT REFERENCES PERSON(ID) ON DELETE CASCADE,
  TRACK_ID TEXT NOT NULL,

  PRIMARY KEY (ID, TRACK_ID)
);

-- Aggregate Contest ------------------------------------

CREATE TABLE CONTEST(
  ID BIGSERIAL PRIMARY KEY,
  CONTEST_ID TEXT UNIQUE NOT NULL,
  TITLE TEXT,
  START_TIME INTEGER ,
  END_TIME INTEGER ,
  TIMEZONE TEXT,
  PLACE TEXT,
  COUNTRY TEXT,
  HQ_LAT REAL,
  HQ_LON REAL
);

CREATE TABLE PARTICIPANT(
  ID BIGINT REFERENCES CONTEST(ID),
  PARTICIPANT_ID TEXT ,
  ROLE TEXT NOT NULL,
  -- for paragliders
  GLIDER TEXT,
  CONTEST_NUMBER TEXT,
  DESCRIPTION TEXT,
  -- person, transport
  TYPE TEXT NOT NULL,

  PRIMARY KEY (ID, PARTICIPANT_ID)
);

CREATE TABLE CONTEST_RACE(
  ID BIGINT REFERENCES CONTEST(ID),
  RACE_ID TEXT,

  PRIMARY KEY (RACE_ID, ID)
);

-- Aggregate Race --------------------------------------

CREATE TABLE RACE_TYPE(
  ID BIGSERIAL PRIMARY KEY,
  -- opendistance, racetogoal, speedrun etc.
  TYPE TEXT UNIQUE NOT NULL
);
INSERT INTO RACE_TYPE(TYPE) VALUES ('racetogoal'), ('speedrun'),
('opendistance');

CREATE TABLE RACE(
  ID BIGSERIAL PRIMARY KEY,
  RACE_ID TEXT UNIQUE NOT NULL,
  TITLE TEXT,
  START_TIME INTEGER NOT NULL,
  END_TIME INTEGER NOT NULL,
  TIMEZONE TEXT NOT NULL ,
  RACE_TYPE BIGINT REFERENCES RACE_TYPE(ID),
  CHECKPOINTS TEXT NOT NULL,
  AUX_FIELDS TEXT
);

CREATE TABLE PARAGLIDER(
  ID BIGINT REFERENCES RACE(ID) ON DELETE CASCADE ,
  PERSON_ID TEXT NOT NULL,
  CONTEST_NUMBER TEXT,
  COUNTRY TEXT NOT NULL ,
  GLIDER TEXT NOT NULL ,
  TRACKER_ID TEXT ,
  NAME TEXT NOT NULL ,
  SURNAME TEXT NOT NULL ,

  PRIMARY KEY (ID, PERSON_ID)
);

CREATE TABLE PARAGLIDER_TRACKS (
  ID BIGINT REFERENCES RACE (ID) ON DELETE CASCADE,
  PERSON_ID TEXT ,
  TRACK_ID TEXT UNIQUE,

  PRIMARY KEY (ID, PERSON_ID)
);


