-- Aggregate Race --------------------------------------

CREATE TABLE RACE_TYPE(
  ID BIGSERIAL PRIMARY KEY,
  -- opendistance, racetogoal, speedrun etc.
  TYPE TEXT UNIQUE NOT NULL
);

CREATE TABLE RACE(
  ID BIGSERIAL PRIMARY KEY,
  RACE_ID TEXT UNIQUE NOT NULL,
  TITLE TEXT,
  START_TIME INTEGER NOT NULL,
  END_TIME INTEGER NOT NULL,
  MIN_START_TIME INTEGER NOT NULL,
  MAX_END_TIME INTEGER NOT NULL,
  TIMEZONE TEXT NOT NULL ,
  RACE_TYPE BIGINT REFERENCES RACE_TYPE(ID),
  CHECKPOINTS TEXT NOT NULL
);

CREATE TABLE PARAGLIDER(
  ID BIGINT REFERENCES RACE(ID) ON DELETE CASCADE ,
  PERSON_ID TEXT NOT NULL,
  CONTEST_NUMBER TEXT,
  COUNTRY TEXT NOT NULL ,
  GLIDER TEXT NOT NULL ,
  TRACKER_ID TEXT ,
  NAME TEXT NOT NULL ,
  SURNAME TEXT NOT NULL ,

  PRIMARY KEY (ID, PERSON_ID)
);

CREATE TABLE PARAGLIDER_TRACKS (
  ID BIGINT REFERENCES RACE (ID) ON DELETE CASCADE,
  PERSON_ID TEXT ,
  TRACK_ID TEXT UNIQUE,

  PRIMARY KEY (ID, PERSON_ID)
);

-- Insert racetype
INSERT INTO RACE_TYPE(TYPE) VALUES (%s);

-- Insert race
INSERT INTO RACE(
  TITLE, START_TIME, END_TIME, MIN_START_TIME, MAX_END_TIME,
  TIMEZONE, RACE_TYPE, CHECKPOINTS, RACE_ID)
  VALUES (%s, %s, %s, %s, %s, %s, (
      SELECT ID FROM RACE_TYPE WHERE TYPE=%s), %s, %s)
RETURNING ID;

-- Select race
SELECT
  ID, RACE_ID, TITLE, START_TIME, END_TIME, MIN_START_TIME, MAX_END_TIME, TIMEZONE, (SELECT TYPE FROM RACE_TYPE WHERE ID=RACE.ID), CHECKPOINTS
FROM RACE WHERE RACE_ID=%s;

-- Update race
UPDATE RACE SET (TITLE, START_TIME, END_TIME, MIN_START_TIME, MAX_END_TIME, TIMEZONE, RACE_TYPE, CHECKPOINTS) = (%s, %s, %s, %s, %s, %s,  (
      SELECT ID FROM RACE_TYPE WHERE TYPE=%s), %s)
WHERE RACE_ID=%s;

-- Select paragliders
SELECT * FROM PARAGLIDER WHERE ID=%s;

-- Insert paraglider
INSERT INTO PARAGLIDER VALUES (%s, %s, %s, %s, %s, %s, %s, %s);