-- Aggregate Tracker -------------------------

CREATE TABLE DEVICE_TYPE(
  ID SERIAL PRIMARY KEY,
  NAME TEXT
);

INSERT INTO DEVICE_TYPE (NAME) VALUES ('tr203');

CREATE TABLE TRACKER(
  ID BIGSERIAL PRIMARY KEY,
  DEVICE_ID TEXT NOT NULL,
  DEVICE_TYPE INT REFERENCES DEVICE_TYPE(ID) ON DELETE RESTRICT,
  NAME TEXT,
  TRACKER_ID TEXT UNIQUE NOT NULL,
  ASSIGNEE TEXT,

  UNIQUE (DEVICE_ID, DEVICE_TYPE)
);


-- Select Tracker
SELECT
  DEVICE_ID,
  (SELECT NAME FROM DEVICE_TYPE WHERE ID=DEVICE_TYPE),
  NAME, TRACKER_ID, ASSIGNEE, ID
FROM TRACKER
WHERE
  TRACKER_ID = %s;

-- Insert Tracker
INSERT INTO TRACKER(DEVICE_ID, DEVICE_TYPE, NAME, TRACKER_ID, ASSIGNEE)
    VALUES (%s,
            (SELECT ID FROM DEVICE_TYPE WHERE NAME=%s),
            %s, %s, %s)
RETURNING ID;