-- Aggregate Tracker -------------------------

CREATE TABLE DEVICE_TYPE(
  ID SERIAL PRIMARY KEY,
  NAME TEXT
);

INSERT INTO DEVICE_TYPE (NAME) VALUES ('tr203');

CREATE TABLE TRACKER(
  ID BIGSERIAL PRIMARY KEY,
  DEVICE_ID TEXT NOT NULL,
  DEVICE_TYPE INT REFERENCES DEVICE_TYPE(ID) ON DELETE RESTRICT,
  TRACKER_ID TEXT UNIQUE NOT NULL,
  NAME TEXT,

  UNIQUE (DEVICE_ID, DEVICE_TYPE)
);


CREATE TABLE TRACKER_ASSIGNEES(
  ID BIGINT REFERENCES TRACKER(ID) ON DELETE CASCADE PRIMARY KEY ,
  ASSIGNEE_ID TEXT NOT NULL ,
  ASSIGNED_FOR TEXT,

  UNIQUE (ID, ASSIGNED_FOR, ASSIGNEE_ID)
);

CREATE TABLE TRACKER_LAST_POINT(
  ID BIGINT REFERENCES TRACKER(ID) ON DELETE CASCADE PRIMARY KEY ,
  LAT REAL ,
  LON REAL ,
  ALT SMALLINT ,
  TIMESTAMP INTEGER,
  BATTERY SMALLINT,
  SPEED REAL
);


CREATE OR REPLACE FUNCTION add_to_last_point() RETURNS TRIGGER AS $$
        BEGIN
          INSERT INTO tracker_last_point (ID) VALUES (NEW.ID);
          RETURN NEW;
        END;
    $$ LANGUAGE plpgsql;

CREATE TRIGGER to_last_point
    AFTER INSERT ON tracker
    FOR EACH ROW EXECUTE PROCEDURE add_to_last_point();

-- Select Tracker
SELECT
  DEVICE_ID,
  (SELECT NAME FROM DEVICE_TYPE WHERE ID=DEVICE_TYPE),
  TRACKER_ID, NAME, ID
FROM TRACKER
WHERE
  TRACKER_ID = %s;


-- Select all_tracker
SELECT
  TRACKER_ID, DEVICE_ID,
  (SELECT NAME FROM DEVICE_TYPE WHERE ID=DEVICE_TYPE),
  TRACKER_ID, NAME, ID
FROM TRACKER;

-- Select trackers
SELECT
 t.tracker_id, t.name, t.device_id,
  (select name from device_type where id=t.device_type),
 tl.lat, tl.lon, tl.alt,
 tl.timestamp, tl.battery, tl.speed
FROM
  tracker t, tracker_last_point tl
WHERE
  t.id=tl.id;

-- Select last_point
SELECT LAT, LON, ALT, TIMESTAMP, BATTERY, SPEED
FROM TRACKER_LAST_POINT WHERE ID=%s;

-- Select assignee
SELECT
  ASSIGNEE_ID, ASSIGNED_FOR
FROM TRACKER_ASSIGNEES
WHERE
  ID = %s;

-- Insert Tracker
INSERT INTO TRACKER(DEVICE_ID, DEVICE_TYPE, NAME, TRACKER_ID)
    VALUES (%s,
            (SELECT ID FROM DEVICE_TYPE WHERE NAME=%s),
            %s, %s)
RETURNING ID;

-- Update Tracker
UPDATE TRACKER SET
  DEVICE_ID=%s,
  DEVICE_TYPE=(SELECT ID FROM DEVICE_TYPE WHERE NAME=%s),
  NAME=%s
WHERE TRACKER_ID=%s;

-- Update last_point
UPDATE TRACKER_LAST_POINT SET
  LAT = %s,
  LON = %s,
  ALT = %s,
  TIMESTAMP=%s,
  BATTERY=%s,
  SPEED=%s
WHERE ID=(SELECT ID FROM TRACKER WHERE DEVICE_ID=%s);