-- Aggregate Tracker -------------------------

CREATE TABLE DEVICE_TYPE(
  ID SERIAL PRIMARY KEY,
  NAME TEXT
);

INSERT INTO DEVICE_TYPE (NAME) VALUES ('tr203');

CREATE TABLE TRACKER(
  ID BIGSERIAL PRIMARY KEY,
  DEVICE_ID TEXT NOT NULL,
  DEVICE_TYPE INT REFERENCES DEVICE_TYPE(ID) ON DELETE RESTRICT,
  TRACKER_ID TEXT UNIQUE NOT NULL,
  NAME TEXT,

  UNIQUE (DEVICE_ID, DEVICE_TYPE)
);


CREATE TABLE TRACKER_ASSIGNEES(
  ID BIGINT REFERENCES TRACKER(ID) ON DELETE CASCADE PRIMARY KEY ,
  ASSIGNEE_ID TEXT NOT NULL ,
  ASSIGNED_FOR TEXT,

  UNIQUE (ID, ASSIGNED_FOR, ASSIGNEE_ID)
);


-- Select Tracker
SELECT
  DEVICE_ID,
  (SELECT NAME FROM DEVICE_TYPE WHERE ID=DEVICE_TYPE),
  TRACKER_ID, NAME, ID
FROM TRACKER
WHERE
  TRACKER_ID = %s;

-- Select assignee
SELECT
  ASSIGNEE_ID, ASSIGNED_FOR
FROM TRACKER_ASSIGNEES
WHERE
  ID = %s;

-- Insert Tracker
INSERT INTO TRACKER(DEVICE_ID, DEVICE_TYPE, NAME, TRACKER_ID)
    VALUES (%s,
            (SELECT ID FROM DEVICE_TYPE WHERE NAME=%s),
            %s, %s)
RETURNING ID;

-- Update Tracker
UPDATE TRACKER SET
  DEVICE_ID=%s,
  DEVICE_TYPE=(SELECT ID FROM DEVICE_TYPE WHERE NAME=%s),
  NAME=%s
WHERE TRACKER_ID=%s;