-- Aggregate Transport -----------------------------------------
CREATE TABLE TRANSPORT_TYPE(
  ID SERIAL PRIMARY KEY ,
  TRANSPORT_TYPE TEXT UNIQUE NOT NULL
);

INSERT INTO TRANSPORT_TYPE(TRANSPORT_TYPE) VALUES ('bus'), ('car'),
('motorcycle'), ('helicopter');

CREATE TABLE TRANSPORT(
  ID BIGSERIAL PRIMARY KEY ,
  TRANSPORT_ID TEXT UNIQUE NOT NULL ,
  TITLE TEXT NOT NULL ,
  TYPE INT REFERENCES TRANSPORT_TYPE(ID) NOT NULL ,
  DESCRIPTION TEXT
);

-- Select transport
SELECT
  ID, TRANSPORT_ID, TITLE,
  (SELECT TRANSPORT_TYPE FROM TRANSPORT_TYPE WHERE ID=TYPE),
  DESCRIPTION
FROM TRANSPORT
WHERE
  TRANSPORT_ID = %s;

-- Select all_transport
SELECT
  TRANSPORT_ID, ID, TRANSPORT_ID, TITLE,
  (SELECT TRANSPORT_TYPE FROM TRANSPORT_TYPE WHERE ID=TYPE),
  DESCRIPTION
FROM TRANSPORT;

-- Insert transport
INSERT INTO TRANSPORT(TITLE, TYPE, DESCRIPTION, TRANSPORT_ID)
    VALUES (%s,
            (SELECT ID FROM TRANSPORT_TYPE WHERE TRANSPORT_TYPE=%s),
            %s, %s)
RETURNING ID;


-- Update transport
UPDATE TRANSPORT SET
  TITLE=%s,
  TYPE=(SELECT ID FROM TRANSPORT_TYPE WHERE TRANSPORT_TYPE=%s),
  DESCRIPTION=%s
WHERE TRANSPORT_ID=%s;
