insert into track_type (name) values('online');

-- Aggregate Tracker -------------------------

CREATE TABLE DEVICE_TYPE(
  ID SERIAL PRIMARY KEY,
  NAME TEXT
);

INSERT INTO DEVICE_TYPE (NAME) VALUES ('tr203');

CREATE TABLE TRACKER(
  ID BIGSERIAL PRIMARY KEY,
  DEVICE_ID TEXT NOT NULL,
  DEVICE_TYPE INT REFERENCES DEVICE_TYPE(ID) ON DELETE RESTRICT,
  TRACKER_ID TEXT UNIQUE NOT NULL,
  NAME TEXT,

  UNIQUE (DEVICE_ID, DEVICE_TYPE)
);


CREATE TABLE TRACKER_ASSIGNEES(
  ID BIGINT REFERENCES TRACKER(ID) ON DELETE CASCADE PRIMARY KEY ,
  ASSIGNEE_ID TEXT NOT NULL ,
  ASSIGNED_FOR TEXT,

  UNIQUE (ID, ASSIGNED_FOR, ASSIGNEE_ID)
);


CREATE TABLE ORGANIZATOR(
  ID BIGINT REFERENCES RACE(ID) ON DELETE CASCADE ,
  PERSON_ID TEXT NOT NULL,
  DESCRIPTION TEXT ,
  TRACKER_ID TEXT ,

  PRIMARY KEY (ID, PERSON_ID)
);

CREATE TABLE PERSON_DATA(
  ID BIGINT REFERENCES PERSON(ID) ON DELETE CASCADE ,
  DATA_TYPE TEXT NOT NULL ,
  DATA_VALUE TEXT NOT NULL,

  PRIMARY KEY (ID, DATA_TYPE, DATA_VALUE)
);

