CREATE UNIQUE INDEX UNIQUE_PHONE
ON PERSON_DATA (ID, DATA_VALUE)
WHERE DATA_TYPE='phone';

CREATE TABLE TRANSPORT_TYPE(
  ID SERIAL PRIMARY KEY ,
  TRANSPORT_TYPE TEXT UNIQUE NOT NULL
);

INSERT INTO TRANSPORT_TYPE(TRANSPORT_TYPE) VALUES ('bus'), ('car'),
('motorcycle'), ('helicopter');

CREATE TABLE TRANSPORT(
  ID BIGSERIAL PRIMARY KEY ,
  TRANSPORT_ID TEXT UNIQUE NOT NULL ,
  TITLE TEXT NOT NULL ,
  TYPE INT REFERENCES TRANSPORT_TYPE(ID) NOT NULL ,
  DESCRIPTION TEXT
);

CREATE TABLE RACE_TRANSPORT(
  ID BIGINT REFERENCES RACE(ID) ON DELETE CASCADE ,
  TRANSPORT_ID TEXT NOT NULL ,
  DESCRIPTION TEXT ,
  TITLE TEXT ,
  TRACKER_ID TEXT NOT NULL ,
  TYPE TEXT NOT NULL ,

  PRIMARY KEY (ID, TRANSPORT_ID)
);

CREATE TABLE CONTEST_RETRIEVE_ID(
  ID BIGINT REFERENCES CONTEST(ID) ON DELETE CASCADE PRIMARY KEY ,
  RETRIEVE_ID TEXT
)